# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |    
    npm install    
  displayName: 'NodeJs packages installation'

- script: |
    npm install -g @angular/cli    
    cd app_public
    npm install       
  displayName: 'Angular packages installation'

- script: |      
    cd app_public       
    ng test 
  displayName: 'Angular Test'
- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test-results*.xml **/e2e-results-junit*.xml '
  inputs:
    testResultsFiles: |
     **/test-results*.xml
     **/e2e-results-junit*.xml

    mergeTestResults: true
  continueOnError: true
  condition: succeededOrFailed()

- script: |
    cd app_public
    ng build --prod --output-path build
  displayName: 'Angular Build into build directory'


  